//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csY2S2_cs_project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int Id { get; set; }
        public string productName { get; set; }
        public string ProductId { get; set; }
        public string totalPrice { get; set; }
        public int customersId { get; set; }
    
        public virtual customers customer { get; set; }
    }
}
