//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csY2S2_cs_project.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string password { get; set; }
        public string userName { get; set; }
        public int roleId { get; set; }
    
        public virtual role role { get; set; }
    }
}
