// <auto-generated />
namespace csY2S2_cs_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Id));
        
        string IMigrationMetadata.Id
        {
            get { return "202104291809250_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
